services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: football_info
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  
  redis:
    image: redis:7
    ports: 
      - 6379:6379


volumes:
  postgres_data: